# Generated by Django 5.1.3 on 2024-11-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
